### ISSUE TITLE
transition matrix

### ISSUE THREAD

**Issue by jksr** [ratschlab/SOM-VAE#9]
Hi,

I think this is really cool. just have two questions:

How could I extract the markov model learnt?

I don't see the code where the model update the transition probabilities. Is that in the optimization step? If so how the sum of the probabilities are maintained?

Thanks in advance for any help!

**Comment by fortuin** [comment]
Hey, thanks for reaching out and for your patience.
The transition probabilities are defined here: https://github.com/ratschlab/SOM-VAE/blob/master/som_vae/somvae_model.py#L176
As you can see, the actual trainable parameters are unnormalized probabilities, but the ones returned by the function and used in the model are normalized. Since the unnormalized probabilities (`probabilities_raw` in the code) are a trainable tf.Variable, they are updated together with the other model parameters during training.
Hope this helps!
